# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
ctrl-alt-l = '''exec-and-forget osascript -e '
tell application "System Events" to sleep
' '''

# ctrl-k = '''exec-and-forget osascript -e '
#     tell application "System Events"
#       set frontApp to name of first application process whose frontmost is true
#     end tell
# 
#     if frontApp is not "Slack" then
#       tell application "System Events"
#         set appNames to name of every process whose background only is false
#       end tell
# 
#       set chosenApp to choose from list appNames with prompt "Switch to application:"
#       if chosenApp is not false then
#         tell application (item 1 of chosenApp) to activate
#       end if
#     end if
#   '
# '''
# ctrl-w = '''exec-and-forget osascript -e '
#   tell application "System Events"
#     set frontApp to name of first application process whose frontmost is true
#   end tell
# 
#   if frontApp is "Google Chrome" then
#     tell application "Google Chrome"
#       if (count of windows) > 0 and (count of tabs of front window) > 1 then
#         close active tab of front window
#       else
#         close front window
#       end if
#     end tell
# # else
# #    try
# #      tell application frontApp to close front window
# #    end try
#   end if
# ' '''
alt-shift-q = '''exec-and-forget osascript -e '
tell application "System Events"
    set frontApp to name of first application process whose frontmost is true
    tell process frontApp
        try
            set win to front window
            perform action "AXPress" of (first button whose subrole is "AXCloseButton") of win
        end try
    end tell
end tell
' '''
ctrl-t = '''exec-and-forget osascript -e '
  tell application "System Events"
    set frontApp to name of first application process whose frontmost is true
  end tell

  if frontApp is "Google Chrome" then
    tell application "Google Chrome"
      make new tab at end of tabs of front window
      activate
    end tell
  end if
' '''
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "iTerm"
  activate
  try
    set newWindow to (create window with default profile)
  on error
    set newTab to (create tab with default profile)
  end try
end tell'
    '''

alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-left = "focus left"
alt-down = "focus down"
alt-up = "focus up"
alt-right = "focus right"

# Move focused window
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-left = "move left"
alt-shift-down = "move down"
alt-shift-up = "move up"
alt-shift-right = "move right"

# Split orientation
ctrl-n = "split horizontal"
# alt-v = "split vertical"

# Fullscreen
alt-f = "fullscreen"

# Layouts
alt-s = "layout v_accordion"
alt-w = "layout h_accordion"
alt-e = "layout tiles horizontal vertical"

# Toggle tiling / floating
alt-shift-space = "layout floating tiling"

# Toggle focus between tiling/floating (not directly supported)
# alt-space = "focus mode_toggle"  # Currently not implemented in Aerospace

# Focus parent (not supported)
# alt-a = "focus parent"

# Workspaces
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-0 = "workspace 10"

alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-0 = "move-node-to-workspace 10"

# i3 wraps focus by default

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
l = 'resize width -50'
k = 'resize height +50'
j = 'resize height -50'
h = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack|Spotify'
run = ['layout tiling', 'move-node-to-workspace 3']
